In [3]:
import sys
sys.path.append(r"C:\Users\Lenovo\OneDrive - Retailstat, LLC\Documents\DataDesk")
import pandas as pd
from config import *

In [4]:
df = pd.read_excel(r"C:\Users\Lenovo\OneDrive - Retailstat, LLC\Documents\DataDesk\test\Sample\Grocery_Task_sample.xlsx")

In [5]:
df.head()

,Category,List ID,List Name,ALI,Polygon Status,Store Name,Address,City,State,ZIP,...,Latitude,Longitude,Parent ALI,Parent Store Name,Parent List Name,HideTraffic,HideFromApp,LastUpdated,hideTrafficFor,constructionFlag
0,grocery,9,Acme Markets,9242557-000000,NaN,Acme Markets,180 W Girard Ave,Philadelphia,PA,19123,...,39.969202,-75.139241,8430000003-000000,Shops at Schmidt's,Sterling Organization,1.0,0.0,2026-02-01,"manual,",Multi-Level
1,grocery,9,Acme Markets,9242561-000000,NaN,Acme Markets,1001 South St,Philadelphia,PA,19147,...,39.942987,-75.158792,NaN,NaN,NaN,1.0,0.0,2026-02-01,"manual,",Multi-Level
2,grocery,9,Acme Markets,9242571-000000,NaN,Acme Markets,19-21 Ave At Port Imperial,West New York,NJ,7093,...,40.782118,-74.006760,NaN,NaN,NaN,1.0,0.0,2026-02-01,"manual,",Multi-Level
3,grocery,9,Acme Markets,9242573-000000,NaN,Acme Markets,510 Valley Rd,Montclair,NJ,7043,...,40.837249,-74.207844,13105000-1200010140,510-516 Valley Road,Properties,NaN,0.0,2026-02-01,NaN,Multi-Level
4,grocery,9,Acme Markets,9242640-000000,NaN,Acme Markets,4001 Walnut St,Philadelphia,PA,19104,...,39.954554,-75.202901,NaN,NaN,NaN,1.0,0.0,2026-02-01,"manual,",Multi-Level

In [6]:
def total_record(dataframe):
    return len(dataframe)

total_record(df)

534

In [7]:
def total_unique_retailers(dataframe):
    return dataframe[LIST_NAME_COL].unique()

total_unique_retailers(df)

<ArrowStringArray>
[                 'Acme Markets',                    'Albertsons',
 'Andronico's Community Markets',                    'Balducci's',
                   'City Market',        'Costco Wholesale Corp.',
          'Dillons Supermarkets',                   'Food 4 Less',
                     'Food Lion',                    'Fred Meyer',
      'Fry's Food & Drug Stores',                    'Giant Food',
             'Giant Food Stores',         'Giant Heirloom Market',
        'Hannaford Supermarkets',                 'Harris Teeter',
                        'Hy-Vee',                    'Jewel-Osco',
                  'King Soopers',                        'Kroger',
                       'Lidl US',                     'Mariano's',
                 'Market Street',                     'Pavilions',
                  'Pick 'n Save',          'Publix Super Markets',
    'QFC (Quality Food Centers)',                        'Ralphs',
                       'Safeway',                  'Safeway Fuel',
    'Smith's Food & Drug Stores',                   'Star Market',
                   'Stop & Shop',     'Tom Thumb Food & Pharmacy',
                  'Trader Joe's',            'Whole Foods Market']
Length: 36, dtype: str

In [8]:
def total_unique_retailers_count(dataframe):
    return dataframe[LIST_NAME_COL].nunique()

total_unique_retailers_count(df)

36

In [9]:
def records_per_retailer(dataframe):
    return dataframe[LIST_NAME_COL].value_counts()

records_per_retailer(df)

List Name
Trader Joe's                     132
Whole Foods Market               111
Publix Super Markets              50
Food Lion                         26
Safeway                           25
Costco Wholesale Corp.            24
Lidl US                           21
Kroger                            20
Harris Teeter                     14
Giant Food                        11
Dillons Supermarkets               9
Hy-Vee                             9
Giant Food Stores                  7
Hannaford Supermarkets             7
Stop & Shop                        7
QFC (Quality Food Centers)         6
Ralphs                             6
Star Market                        6
Acme Markets                       5
King Soopers                       4
Mariano's                          4
Market Street                      4
Tom Thumb Food & Pharmacy          4
Fry's Food & Drug Stores           3
Giant Heirloom Market              3
Jewel-Osco                         3
Balducci's                         2
Fred Meyer                         2
Smith's Food & Drug Stores         2
Albertsons                         1
Andronico's Community Markets      1
City Market                        1
Food 4 Less                        1
Pavilions                          1
Pick 'n Save                       1
Safeway Fuel                       1
Name: count, dtype: int64

In [10]:
def construction_flag_breakdown(dataframe):
    # fill NaN in construction flag with NORMAL label first
    df = dataframe.copy()
    df[CONSTRUCTION_FLAG_COL] = df[CONSTRUCTION_FLAG_COL].fillna(NORMAL)
    
    # group and count
    breakdown_df = df.groupby([LIST_NAME_COL, CONSTRUCTION_FLAG_COL]).size().unstack(fill_value=0)
    
    # add total column
    breakdown_df["Total"] = breakdown_df.sum(axis=1)
    
    return breakdown_df

construction_flag_breakdown(df)

constructionFlag,Construction,Mall Tenant,Multi-Level,Normal,Within-Store/Kiosk,Total
List Name,,,,,,
Acme Markets,0,0,5,0,0,5
Albertsons,0,0,1,0,0,1
Andronico's Community Markets,0,0,1,0,0,1
Balducci's,0,0,2,0,0,2
City Market,0,0,0,0,1,1
Costco Wholesale Corp.,11,0,2,11,0,24
Dillons Supermarkets,0,0,0,3,6,9
Food 4 Less,0,0,1,0,0,1
Food Lion,2,0,0,24,0,26
Fred Meyer,0,0,1,0,1,2
Fry's Food & Drug Stores,0,0,1,2,0,3
Giant Food,0,0,11,0,0,11
Giant Food Stores,0,0,6,1,0,7
Giant Heirloom Market,0,0,3,0,0,3
Hannaford Supermarkets,0,0,0,7,0,7
Harris Teeter,0,0,14,0,0,14
Hy-Vee,0,1,6,0,2,9
Jewel-Osco,0,0,3,0,0,3
King Soopers,1,0,2,1,0,4
Kroger,2,0,4,11,3,20
Lidl US,1,2,8,10,0,21
Mariano's,0,0,4,0,0,4
Market Street,3,0,1,0,0,4
Pavilions,0,0,1,0,0,1
Pick 'n Save,0,0,1,0,0,1
Publix Super Markets,14,0,21,15,0,50
QFC (Quality Food Centers),0,0,6,0,0,6
Ralphs,0,0,6,0,0,6
Safeway,0,1,20,4,0,25
Safeway Fuel,1,0,0,0,0,1
Smith's Food & Drug Stores,0,0,0,2,0,2
Star Market,0,0,6,0,0,6
Stop & Shop,0,0,7,0,0,7
Tom Thumb Food & Pharmacy,0,0,2,2,0,4
Trader Joe's,6,0,92,34,0,132
Whole Foods Market,2,1,102,6,0,111

In [11]:
def polygon_status_breakdown(dataframe):
    # fill NaN in polygon status with NORMAL label first
    df = dataframe.copy()
    df[POLYGON_STATUS_COL] = df[POLYGON_STATUS_COL].fillna(NORMAL)
    
    # group and count
    polygon_status_df = df.groupby([LIST_NAME_COL, POLYGON_STATUS_COL]).size().unstack(fill_value=0)
    
    # add total column
    polygon_status_df["Total"] = polygon_status_df.sum(axis=1)
    
    return polygon_status_df

polygon_status_breakdown(df)

Polygon Status                 Normal  Total
List Name
Acme Markets                        5      5
Albertsons                          1      1
Andronico's Community Markets       1      1
Balducci's                          2      2
City Market                         1      1
Costco Wholesale Corp.             24     24
Dillons Supermarkets                9      9
Food 4 Less                         1      1
Food Lion                          26     26
Fred Meyer                          2      2
Fry's Food & Drug Stores            3      3
Giant Food                         11     11
Giant Food Stores                   7      7
Giant Heirloom Market               3      3
Hannaford Supermarkets              7      7
Harris Teeter                      14     14
Hy-Vee                              9      9
Jewel-Osco                          3      3
King Soopers                        4      4
Kroger                             20     20
Lidl US                            21     21
Mariano's                           4      4
Market Street                       4      4
Pavilions                           1      1
Pick 'n Save                        1      1
Publix Super Markets               50     50
QFC (Quality Food Centers)          6      6
Ralphs                              6      6
Safeway                            25     25
Safeway Fuel                        1      1
Smith's Food & Drug Stores          2      2
Star Market                         6      6
Stop & Shop                         7      7
Tom Thumb Food & Pharmacy           4      4
Trader Joe's                      132    132
Whole Foods Market                111    111

In [15]:
def duplicate_ali_analysis(df):
    
    duplicates = df[df[ALI_COL].duplicated(keep=False)]
    
    duplicate_count = df[ALI_COL].duplicated().sum()
    unique_count    = df[ALI_COL].nunique()
    total           = len(df)
    
    return {
        "total"           : total,
        "unique_ali"      : unique_count,
        "duplicate_count" : duplicate_count,
        "duplicate_rows"  : duplicates    # actual duplicate records
    }

duplicate_ali_analysis(df)

{'total': 534,
 'unique_ali': 534,
 'duplicate_count': np.int64(0),
 'duplicate_rows': Empty DataFrame
 Columns: [Category, List ID, List Name, ALI, Polygon Status, Store Name, Address, City, State, ZIP, Geo Accuracy, SQFT, Manual SQFT, SC, User, Type, Date Effective, Latitude, Longitude, Parent ALI, Parent Store Name, Parent List Name, HideTraffic, HideFromApp, LastUpdated, hideTrafficFor, constructionFlag]
 Index: []

 [0 rows x 27 columns]}

In [18]:
def get_full_analysis(df):
    return {
        "total_records"     : total_record(df),
        "unique_retailers"  : total_unique_retailers(df),
        "per_retailer"      : records_per_retailer(df),
        "construction_flag" : construction_flag_breakdown(df),
        "polygon_status"    : polygon_status_breakdown(df),
        "duplicate_ali"     : duplicate_ali_analysis(df)  # ← added
    }

In [19]:
get_full_analysis(df)

{'total_records': 534,
 'unique_retailers': <ArrowStringArray>
 [                 'Acme Markets',                    'Albertsons',
  'Andronico's Community Markets',                    'Balducci's',
                    'City Market',        'Costco Wholesale Corp.',
           'Dillons Supermarkets',                   'Food 4 Less',
                      'Food Lion',                    'Fred Meyer',
       'Fry's Food & Drug Stores',                    'Giant Food',
              'Giant Food Stores',         'Giant Heirloom Market',
         'Hannaford Supermarkets',                 'Harris Teeter',
                         'Hy-Vee',                    'Jewel-Osco',
                   'King Soopers',                        'Kroger',
                        'Lidl US',                     'Mariano's',
                  'Market Street',                     'Pavilions',
                   'Pick 'n Save',          'Publix Super Markets',
     'QFC (Quality Food Centers)',                        'Ralphs',
                        'Safeway',                  'Safeway Fuel',
     'Smith's Food & Drug Stores',                   'Star Market',
                    'Stop & Shop',     'Tom Thumb Food & Pharmacy',
                   'Trader Joe's',            'Whole Foods Market']
 Length: 36, dtype: str,
 'per_retailer': List Name
 Trader Joe's                     132
 Whole Foods Market               111
 Publix Super Markets              50
 Food Lion                         26
 Safeway                           25
 Costco Wholesale Corp.            24
 Lidl US                           21
 Kroger                            20
 Harris Teeter                     14
 Giant Food                        11
 Dillons Supermarkets               9
 Hy-Vee                             9
 Giant Food Stores                  7
 Hannaford Supermarkets             7
 Stop & Shop                        7
 QFC (Quality Food Centers)         6
 Ralphs                             6
 Star Market                        6
 Acme Markets                       5
 King Soopers                       4
 Mariano's                          4
 Market Street                      4
 Tom Thumb Food & Pharmacy          4
 Fry's Food & Drug Stores           3
 Giant Heirloom Market              3
 Jewel-Osco                         3
 Balducci's                         2
 Fred Meyer                         2
 Smith's Food & Drug Stores         2
 Albertsons                         1
 Andronico's Community Markets      1
 City Market                        1
 Food 4 Less                        1
 Pavilions                          1
 Pick 'n Save                       1
 Safeway Fuel                       1
 Name: count, dtype: int64,
 'construction_flag': constructionFlag               Construction  Mall Tenant  Multi-Level  Normal  \
 List Name
 Acme Markets                              0            0            5       0
 Albertsons                                0            0            1       0
 Andronico's Community Markets             0            0            1       0
 Balducci's                                0            0            2       0
 City Market                               0            0            0       0
 Costco Wholesale Corp.                   11            0            2      11
 Dillons Supermarkets                      0            0            0       3
 Food 4 Less                               0            0            1       0
 Food Lion                                 2            0            0      24
 Fred Meyer                                0            0            1       0
 Fry's Food & Drug Stores                  0            0            1       2
 Giant Food                                0            0           11       0
 Giant Food Stores                         0            0            6       1
 Giant Heirloom Market                     0            0            3       0
 Hannaford Supermarkets                    0            0            0       7
 Harris Teeter                             0            0           14       0
 Hy-Vee                                    0            1            6       0
 Jewel-Osco                                0            0            3       0
 King Soopers                              1            0            2       1
 Kroger                                    2            0            4      11
 Lidl US                                   1            2            8      10
 Mariano's                                 0            0            4       0
 Market Street                             3            0            1       0
 Pavilions                                 0            0            1       0
 Pick 'n Save                              0            0            1       0
 Publix Super Markets                     14            0           21      15
 QFC (Quality Food Centers)                0            0            6       0
 Ralphs                                    0            0            6       0
 Safeway                                   0            1           20       4
 Safeway Fuel                              1            0            0       0
 Smith's Food & Drug Stores                0            0            0       2
 Star Market                               0            0            6       0
 Stop & Shop                               0            0            7       0
 Tom Thumb Food & Pharmacy                 0            0            2       2
 Trader Joe's                              6            0           92      34
 Whole Foods Market                        2            1          102       6

 constructionFlag               Within-Store/Kiosk  Total
 List Name
 Acme Markets                                    0      5
 Albertsons                                      0      1
 Andronico's Community Markets                   0      1
 Balducci's                                      0      2
 City Market                                     1      1
 Costco Wholesale Corp.                          0     24
 Dillons Supermarkets                            6      9
 Food 4 Less                                     0      1
 Food Lion                                       0     26
 Fred Meyer                                      1      2
 Fry's Food & Drug Stores                        0      3
 Giant Food                                      0     11
 Giant Food Stores                               0      7
 Giant Heirloom Market                           0      3
 Hannaford Supermarkets                          0      7
 Harris Teeter                                   0     14
 Hy-Vee                                          2      9
 Jewel-Osco                                      0      3
 King Soopers                                    0      4
 Kroger                                          3     20
 Lidl US                                         0     21
 Mariano's                                       0      4
 Market Street                                   0      4
 Pavilions                                       0      1
 Pick 'n Save                                    0      1
 Publix Super Markets                            0     50
 QFC (Quality Food Centers)                      0      6
 Ralphs                                          0      6
 Safeway                                         0     25
 Safeway Fuel                                    0      1
 Smith's Food & Drug Stores                      0      2
 Star Market                                     0      6
 Stop & Shop                                     0      7
 Tom Thumb Food & Pharmacy                       0      4
 Trader Joe's                                    0    132
 Whole Foods Market                              0    111  ,
 'polygon_status': Polygon Status                 Normal  Total
 List Name
 Acme Markets                        5      5
 Albertsons                          1      1
 Andronico's Community Markets       1      1
 Balducci's                          2      2
 City Market                         1      1
 Costco Wholesale Corp.             24     24
 Dillons Supermarkets                9      9
 Food 4 Less                         1      1
 Food Lion                          26     26
 Fred Meyer                          2      2
 Fry's Food & Drug Stores            3      3
 Giant Food                         11     11
 Giant Food Stores                   7      7
 Giant Heirloom Market               3      3
 Hannaford Supermarkets              7      7
 Harris Teeter                      14     14
 Hy-Vee                              9      9
 Jewel-Osco                          3      3
 King Soopers                        4      4
 Kroger                             20     20
 Lidl US                            21     21
 Mariano's                           4      4
 Market Street                       4      4
 Pavilions                           1      1
 Pick 'n Save                        1      1
 Publix Super Markets               50     50
 QFC (Quality Food Centers)          6      6
 Ralphs                              6      6
 Safeway                            25     25
 Safeway Fuel                        1      1
 Smith's Food & Drug Stores          2      2
 Star Market                         6      6
 Stop & Shop                         7      7
 Tom Thumb Food & Pharmacy           4      4
 Trader Joe's                      132    132
 Whole Foods Market                111    111,
 'duplicate_ali': {'total': 534,
  'unique_ali': 534,
  'duplicate_count': np.int64(0),
  'duplicate_rows': Empty DataFrame
  Columns: [Category, List ID, List Name, ALI, Polygon Status, Store Name, Address, City, State, ZIP, Geo Accuracy, SQFT, Manual SQFT, SC, User, Type, Date Effective, Latitude, Longitude, Parent ALI, Parent Store Name, Parent List Name, HideTraffic, HideFromApp, LastUpdated, hideTrafficFor, constructionFlag]
  Index: []

  [0 rows x 27 columns]}}